<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.15" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\ApplicationProjects\ManagmentSystem\ManagmentSystem.csproj" />
    <ProjectReference Include="..\..\ApplicationProjects\WPF_UI\WPF_UI.csproj" />
    <ProjectReference Include="..\..\DbContext\Account.DbContext.csproj" />
    <ProjectReference Include="..\..\Framework\DataTransferObjects\DataTransferObjects.csproj" />
    <ProjectReference Include="..\..\LayerProjects\Account.BL\Account.BL.csproj" />
    <ProjectReference Include="..\..\LayerProjects\Account.DAL\Account.DAL.csproj" />
    <ProjectReference Include="..\..\LayerProjects\Account.DPL\Account.DPL.csproj" />
    <ProjectReference Include="..\..\LayerProjects\Account.VM\Account.VM.csproj" />
  </ItemGroup>

</Project>
