<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contract\Account.CON.csproj" />
    <ProjectReference Include="..\..\Data\Account.DTO\Account.DTO.csproj" />
    <ProjectReference Include="..\..\DbContext\Account.DbContext.csproj" />
    <ProjectReference Include="..\..\Framework\DataTrasferObjectInterfaces\DataTrasferObjectInterfaces.csproj" />
    <ProjectReference Include="..\..\ServiceProjects\BusinessProcessHandlers\BusinessProcessHandlers.csproj" />
    <ProjectReference Include="..\..\SystemResourses\SystemResourses.csproj" />
  </ItemGroup>

</Project>
